settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: worker-aged-truth-7545 # unique identifier
    name: worker-aged-truth-7545.antophyscom.workers.dev
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://worker-aged-truth-7545.antophyscom.workers.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: cartrackweb
    name: cartrackweb.catdynamics.co.za
    description: 'Built for anything connected to the Internet.'
    url: 'http://cartrackweb.catdynamics.co.za:8080/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
